# Generated by Django 5.1.2 on 2024-10-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блога')),
                ('description', models.TextField(verbose_name='описания лого')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Лого')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.CharField(max_length=255, verbose_name='количество коменнтарии')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото сотрудника')),
                ('position', models.CharField(max_length=255, verbose_name='Должность сотрудника')),
                ('facebook', models.URLField(verbose_name='Ссылка на facebook')),
                ('twitter', models.URLField(verbose_name='Ссылка на twitter')),
                ('github', models.URLField(verbose_name='Ссылка на Github')),
                ('google', models.URLField(verbose_name='Ссылка на Google +')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
